spring.application.name=backend
spring.docker.compose.file=backend/compose.yaml
spring.datasource.url=jdbc:postgresql://localhost:5432/autoimport_hub
spring.datasource.username=autoimp_user
spring.datasource.password=secret
spring.jpa.hibernate.ddl-auto=validate
